export type AppRoute =
  | "/login"
  | "/onboarding"
  | "/dashboard"
  | "/transactions"
  | "/wallets"
  | "/wallets/:id"
  | "/calendar"
  | "/analytics"
  | "/goals"
  | "/goals/:id"
  | "/debts"
  | "/shared"
  | "/notifications"
  | "/settings"
  | "/settings/categories";
