import { Tags } from "lucide-react";
import { donutRingColor } from "../../lib/reportCharts";
import { useI18n } from "../../i18n";

export type SpendingChartItem = { id: string; name: string; amount: number; percent: number; groupType: "envelope" | "category"; color?: string };
export function SpendingBreakdownChart({ currency, items, onSelect }: { currency: string; items: SpendingChartItem[]; onSelect: (item: SpendingChartItem) => void }) {
  const { t, formatCurrency } = useI18n();
  const total = items.reduce((sum, item) => sum + item.amount, 0);
  if (!items.length || total <= 0) return <div className="mt-4 flex min-h-64 items-center justify-center rounded-xl bg-slate-50 px-4 text-center text-sm font-semibold text-slate-500">{t("analytics.noExpenseCategories") || "No expense categories"}</div>;
  const radius = 48; const circumference = 2 * Math.PI * radius; const gapDeg = 3; const availableDeg = 360 - gapDeg * items.length; let offset = 0;
  const segments = items.map((item, index) => { const length = item.percent / 100 * availableDeg / 360 * circumference; const currentOffset = offset; offset += length + gapDeg / 360 * circumference; return { ...item, color: donutRingColor(index, items.length), dasharray: `${length} ${circumference - length}`, dashoffset: -currentOffset }; });
  return <div className="my-auto flex w-full flex-1 flex-col items-center justify-center gap-6 py-4 md:flex-row md:items-center"><div className="relative mx-auto flex h-55 w-55 max-w-full shrink-0 items-center justify-center md:mx-0"><svg viewBox="0 0 120 120" className="kash-ring-chart h-full w-full -rotate-90">{segments.map((item) => <circle key={`${item.groupType}:${item.id}`} data-segment cx="60" cy="60" r={radius} fill="none" stroke={item.color} strokeWidth="20" strokeLinecap="round" strokeDasharray={item.dasharray} strokeDashoffset={item.dashoffset} className="cursor-pointer" onClick={() => onSelect(item)} />)}</svg><div className="absolute inset-0 flex items-center justify-center p-2 text-center"><div className="min-w-0 max-w-full"><p className="text-[11px] font-bold text-slate-500">{t("dashboard.totalExpense") || "Total Spend"}</p><p className="mt-0.5 max-w-[7rem] truncate text-xs font-extrabold leading-tight text-slate-900 sm:text-sm md:text-base">{formatCurrency(total, currency)}</p></div></div></div><div className="w-full min-w-0 space-y-2.5 md:flex-1">{segments.map((item) => <button type="button" key={`${item.groupType}:${item.id}`} onClick={() => onSelect(item)} className="block w-full min-w-0 rounded-lg text-left text-xs transition hover:bg-slate-50 sm:text-sm"><div className="flex items-center justify-between gap-2.5"><div className="flex min-w-0 items-center gap-2"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: item.color }} /><span className="truncate font-semibold text-slate-700">{item.id === "uncategorized" ? (t("categories.uncategorized") || "Uncategorized") : item.name}</span><span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-slate-100 px-1.5 py-0.5 text-[9px] font-bold text-slate-500">{item.groupType === "envelope" ? <Tags size={10} /> : null}{item.groupType === "envelope" ? (t("budgets.envelope") || "Envelope") : (t("reports.category") || "Category")}</span></div><div className="shrink-0 text-right"><span className="font-bold text-slate-900">{formatCurrency(item.amount, currency)}</span><span className="ml-1.5 text-xs font-semibold text-slate-500">{Math.round(item.percent)}%</span></div></div></button>)}</div></div>;
}
